#!/bin/sh

echo '[git hook] executing gradle spotlessCheck before commit'

# check if there are any unstaged changes
if ! git diff --exit-code --quiet; then
    echo '[git hook] unstaged changes found, skipping stash and spotlessApply'
    exit 0
fi

# run the spotlessCheck with the gradle wrapper
./gradlew spotlessApply --init-script gradle/init.gradle.kts --no-configuration-cache

# store the last exit code in a variable
RESULT=$?

# return the './gradlew spotlessCheck' exit code
exit $RESULT
