#!/bin/sh
# From gist at https://gist.github.com/chadmaughan/5889802

echo '[Pre-Push git hook] executing gradle spotlessCheck before commit'

# stash any unstaged changes
git stash -q --keep-index

# run the spotlessCheck with the gradle wrapper
./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew spotlessCheck' exit code
exit $RESULT
